name: build
on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [lts/*, latest]
    steps:
      - uses: actions/checkout@HEAD
      - uses: actions/setup-node@HEAD
        with:
          node-version: ${{ matrix.version }}
      - run: npm ci
      - run: npm run build
      - name: Test with cypress
        uses: cypress-io/github-action@v4
        env:
          PORT: 8888
        with:
          env: port=$PORT
          start: npm run dev